version: '3'
services: 
  web:
      build: .
      volumes:
        - .:/usr/app/
        - /usr/app/node_modules
      command:  npm run start-dev
      depends_on:
        - postgres
  postgres: 
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: user
        POSTGRES_DB: my_db
    
